"""Repositories: intent-named reads/writes over a SQLAlchemy session.

These methods `flush` (so autogenerated ids/defaults are available) but never
`commit` — the transaction boundary belongs to `transaction()` in `database.py`,
so several repository calls can share one atomic unit of work.

`ChunkRepository.similarity_search` is added in Phase 3 (it needs the embedding
and cosine-distance machinery).
"""
from __future__ import annotations

from sqlalchemy import func, select
from sqlalchemy.orm import Session, joinedload

from db.models import Document, DocumentChunk


class DocumentRepository:
    def __init__(self, db: Session) -> None:
        self._db = db

    def create(self, filename: str, content: str, doc_metadata: dict) -> Document:
        document = Document(
            filename=filename, content=content, doc_metadata=doc_metadata
        )
        self._db.add(document)
        self._db.flush()
        self._db.refresh(document)
        return document

    def get_by_id(self, document_id: int) -> Document | None:
        return self._db.get(Document, document_id)

    def get_by_filename(self, filename: str) -> Document | None:
        statement = select(Document).where(Document.filename == filename)
        return self._db.scalars(statement).first()

    def get_all(self, skip: int = 0, limit: int = 100) -> list[Document]:
        statement = (
            select(Document)
            .order_by(Document.created_at.desc())
            .offset(skip)
            .limit(limit)
        )
        return list(self._db.scalars(statement).all())

    def count(self) -> int:
        return self._db.scalar(select(func.count()).select_from(Document)) or 0


class ChunkRepository:
    def __init__(self, db: Session) -> None:
        self._db = db

    def create_batch(
        self,
        document_id: int,
        chunks: list[str],
        embeddings: list[list[float]],
    ) -> list[DocumentChunk]:
        document_chunks = [
            DocumentChunk(
                document_id=document_id,
                content=content,
                chunk_index=chunk_index,
                embedding=embedding,
            )
            for chunk_index, (content, embedding) in enumerate(zip(chunks, embeddings))
        ]
        self._db.add_all(document_chunks)
        self._db.flush()
        return document_chunks

    def get_document_chunks(self, document_id: int) -> list[DocumentChunk]:
        statement = (
            select(DocumentChunk)
            .where(DocumentChunk.document_id == document_id)
            .order_by(DocumentChunk.chunk_index)
        )
        return list(self._db.scalars(statement).all())

    def similarity_search(
        self, query_embedding: list[float], top_k: int = 5
    ) -> list[tuple[DocumentChunk, float]]:
        distance_expression = DocumentChunk.embedding.cosine_distance(query_embedding)
        score_expression = (1 - distance_expression).label("score")

        statement = (
            select(DocumentChunk, score_expression)
            .options(joinedload(DocumentChunk.document))
            .order_by(distance_expression)
            .limit(top_k)
        )
        return [(chunk, float(score)) for chunk, score in self._db.execute(statement)]